### ISSUE TITLE
Co-publish in Open VSX

### ISSUE THREAD

**Issue by yujikiriki** [gera2ld/markmap-vscode#3] opened 2020-11-09 15:38 UTC
Open VSX is an open-source registry for VS Code extensions. It can be used by any development environment that supports such extensions. See this [article](https://www.eclipse.org/community/eclipse_newsletter/2020/march/1.php) for more information.

It would be cool if this marvellous extension is available in OpenVSX.

The guide to publish it can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

There is a [Github Action](https://github.com/HaaLeo/publish-vscode-extension#readme) to publish the extension to OpenVSX that can be used too.

**Comment by gera2ld** [comment] 2020-11-10 04:21
This is a duplicate of #2 .
It has been published at <https://open-vsx.org/extension/gera2ld/markmap-vscode>.

**Closed by gera2ld** 2020-11-10 04:21 UTC
