### ISSUE TITLE
Code block does not render correctly for some languages

### ISSUE THREAD

**Issue by chymy** [gera2ld/markmap-vscode#7] opened 2020-12-03 06:57 UTC
Usually it doesn't render in vs code. 
vs code version: 1.51.1

but it is ok in `https://markmap.js.org/repl`

**Comment by gera2ld** [comment] 2020-12-03 12:06
What do you mean by `doesn't render`? Can you give an example please?

**Comment by chymy** [comment] 2020-12-04 00:42
eg:
in` vs code`:
![image](https://user-images.githubusercontent.com/9379950/101107081-842d4980-360c-11eb-8eca-6a95b6ac26f0.png)

 in `https://markmap.js.org/repl`
![image](https://user-images.githubusercontent.com/9379950/101107130-9b6c3700-360c-11eb-9e44-a579a94c0be9.png)

**Comment by gera2ld** [comment] 2020-12-04 03:03
Duplicate of gera2ld/markmap#52

**Closed** 2020-12-05 08:43 UTC
